// export { default as getHeader } from './getHeader'
// export { default as getHero } from './getHero'
export { getHeader, getHero, getAbout } from './getSectionsData'

export { default as getPageInfo } from './getPageInfo'
export { default as getProjects } from './getProjects'
export { default as getStacks } from './getStacks'
export { default as getTechnologies } from './getTechnologies'
export { default as getTeam } from './getTeam'
export { default as getPrices } from './getPrices'
